import type { Copy, MobileTab, UiLanguage } from './types';

export const COPY: Record<UiLanguage, Copy> = {
  en: {
    appTitle: 'Calder Mobile',
    appSubtitle: 'Native control companion for sessions, CLI routing, browser tools, and inspect workflows.',
    pairingLinkLabel: 'Desktop pairing link',
    pairingLinkPlaceholder: 'https://.../m/<pairing-id>?t=<token>',
    otpLabel: 'One-time code',
    otpPlaceholder: '123456',
    connectButton: 'Bootstrap Connection',
    connectInProgress: 'Connecting...',
    openLiveControl: 'Open Live Control',
    hideLiveControl: 'Hide Live Control',
    languageButton: 'TR',
    tabs: {
      overview: 'Overview',
      sessions: 'Sessions',
      cli: 'CLI',
      browser: 'Browser',
      inspect: 'Inspect',
      live: 'Live',
    },
    idleStatus: 'Idle',
    waitingStatus: 'Waiting',
    connectedStatus: 'Connected',
    errorStatus: 'Error',
    liveStatusLabel: 'Console status',
    liveConnectionLabel: 'Connection',
    liveConsoleWaiting: 'Waiting for live console telemetry...',
    liveConnectionWaiting: 'Waiting for connection telemetry...',
    liveSessionLabel: 'Live sessions',
    liveSessionEmpty: 'No live sessions yet. Open Live tab and wait for session catalog.',
    switchSessionButton: 'Switch Session',
    switchSessionHint: 'Select a session and switch through the live channel.',
    commandLabel: 'Command deck',
    commandPlaceholder: 'Type command to send into active session',
    sendCommandButton: 'Send Command',
    quickControlsLabel: 'Quick controls',
    quickControlCtrlC: 'Ctrl+C',
    quickControlCtrlL: 'Ctrl+L',
    quickControlEnter: 'Enter',
    quickControlTab: 'Tab',
    browserSessionLabel: 'Browser sessions',
    browserStatusWaiting: 'Waiting for browser control status...',
    browserBackButton: 'Back',
    browserForwardButton: 'Forward',
    browserReloadButton: 'Reload',
    browserInspectButton: 'Inspect',
    browserResponsiveButton: 'Responsive',
    browserPhoneButton: 'iPhone 14',
    inspectPhaseHint: 'Toggle inspect mode from mobile and follow status updates instantly.',
    inspectSelectionLabel: 'Selected element',
    inspectSelectionNone: 'No inspect selection yet. Enable inspect and tap an element first.',
    inspectInstructionLabel: 'Inspect instruction',
    inspectInstructionPlaceholder: 'Describe what should be done for this element',
    inspectSendButton: 'Send Inspect Prompt',
    sectionTitle: {
      overview: 'Control Overview',
      sessions: 'Session Control',
      cli: 'CLI Routing',
      browser: 'Browser Controls',
      inspect: 'Inspect Bridge',
      live: 'Live Control Console',
    },
    sectionCopy: {
      overview: 'Shows desktop health, active device trust, and control readiness in one place.',
      sessions: 'List sessions, switch active session, and send input without leaving mobile.',
      cli: 'Choose provider target and route prompts to the selected CLI session.',
      browser: 'Trigger browser quick actions and monitor viewport state from phone.',
      inspect: 'Start inspect mode, review selected element metadata, and send context to session.',
      live: 'Runs Calder desktop mobile control page inside the native app for full realtime terminal control.',
    },
  },
  tr: {
    appTitle: 'Calder Mobil',
    appSubtitle: 'Oturumlar, CLI yonlendirme, tarayici araclari ve inspect akislari icin native kontrol esligi.',
    pairingLinkLabel: 'Masaustu eslestirme baglantisi',
    pairingLinkPlaceholder: 'https://.../m/<pairing-id>?t=<token>',
    otpLabel: 'Tek kullanimlik kod',
    otpPlaceholder: '123456',
    connectButton: 'Baglantiyi Baslat',
    connectInProgress: 'Baglaniyor...',
    openLiveControl: 'Canli Kontrolu Ac',
    hideLiveControl: 'Canli Kontrolu Gizle',
    languageButton: 'EN',
    tabs: {
      overview: 'Genel',
      sessions: 'Oturumlar',
      cli: 'CLI',
      browser: 'Tarayici',
      inspect: 'Inspect',
      live: 'Canli',
    },
    idleStatus: 'Hazir',
    waitingStatus: 'Bekliyor',
    connectedStatus: 'Bagli',
    errorStatus: 'Hata',
    liveStatusLabel: 'Konsol durumu',
    liveConnectionLabel: 'Baglanti',
    liveConsoleWaiting: 'Canli konsol telemetrisi bekleniyor...',
    liveConnectionWaiting: 'Baglanti telemetrisi bekleniyor...',
    liveSessionLabel: 'Canli oturumlar',
    liveSessionEmpty: 'Henuz canli oturum yok. Canli sekmesini acip katalogu bekleyin.',
    switchSessionButton: 'Oturumu Degistir',
    switchSessionHint: 'Bir oturum secip canli kanal uzerinden degistirin.',
    commandLabel: 'Komut paneli',
    commandPlaceholder: 'Aktif oturuma gonderilecek komutu yazin',
    sendCommandButton: 'Komut Gonder',
    quickControlsLabel: 'Hizli kontroller',
    quickControlCtrlC: 'Ctrl+C',
    quickControlCtrlL: 'Ctrl+L',
    quickControlEnter: 'Enter',
    quickControlTab: 'Tab',
    browserSessionLabel: 'Tarayici oturumlari',
    browserStatusWaiting: 'Tarayici kontrol durumu bekleniyor...',
    browserBackButton: 'Geri',
    browserForwardButton: 'Ileri',
    browserReloadButton: 'Yenile',
    browserInspectButton: 'Inspect',
    browserResponsiveButton: 'Responsive',
    browserPhoneButton: 'iPhone 14',
    inspectPhaseHint: 'Inspect modunu mobilden acip kapatabilir ve durumu anlik izleyebilirsiniz.',
    inspectSelectionLabel: 'Secili element',
    inspectSelectionNone: 'Henuz inspect secimi yok. Once inspect modunda bir elemana dokunun.',
    inspectInstructionLabel: 'Inspect talimati',
    inspectInstructionPlaceholder: 'Bu element icin ne yapilacagini yazin',
    inspectSendButton: 'Inspect Prompt Gonder',
    sectionTitle: {
      overview: 'Kontrol Ozeti',
      sessions: 'Oturum Kontrolu',
      cli: 'CLI Yonlendirme',
      browser: 'Tarayici Kontrolleri',
      inspect: 'Inspect Koprusu',
      live: 'Canli Kontrol Konsolu',
    },
    sectionCopy: {
      overview: 'Masaustu saglik durumu, guvenilen cihaz ve kontrol hazir olma bilgisini tek yerde gosterir.',
      sessions: 'Mobilden cikmadan oturum listesi, aktif oturum degistirme ve giris gonderme.',
      cli: 'Saglayici hedefini secip promptlari secilen CLI oturumuna yonlendir.',
      browser: 'Telefondan tarayici hizli aksiyonlarini tetikle ve viewport durumunu izle.',
      inspect: 'Inspect modunu baslat, secili element bilgisini gor ve oturuma baglam gonder.',
      live: 'Calder masaustu mobil kontrol sayfasini native uygulama icinde calistirarak canli terminal kontrolu saglar.',
    },
  },
};

export const TAB_ORDER: MobileTab[] = ['overview', 'sessions', 'cli', 'browser', 'inspect', 'live'];
