import { StyleSheet } from 'react-native';
import { palette, spacing } from '../theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  content: {
    padding: spacing.lg,
    gap: spacing.lg,
  },
  headerCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: spacing.lg,
    gap: spacing.md,
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  titleWrap: {
    flex: 1,
    gap: spacing.xs,
  },
  title: {
    color: palette.text,
    fontSize: 24,
    fontWeight: '700',
  },
  subtitle: {
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  languageButton: {
    minWidth: 46,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.panelElevated,
  },
  languageButtonText: {
    color: palette.text,
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 0.3,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    gap: spacing.xs,
    backgroundColor: 'rgba(7, 11, 20, 0.7)',
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  panel: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    padding: spacing.lg,
  },
  label: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '600',
    marginBottom: spacing.xs,
  },
  input: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    backgroundColor: palette.panelElevated,
    color: palette.text,
    minHeight: 46,
    paddingHorizontal: spacing.md,
    fontSize: 14,
  },
  primaryActions: {
    marginTop: spacing.lg,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  flexAction: {
    flex: 1,
  },
  connectButton: {
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  connectButtonText: {
    color: palette.bg,
    fontSize: 14,
    fontWeight: '700',
  },
  secondaryAction: {
    minHeight: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelElevated,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  secondaryActionText: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '700',
  },
  connectBusyWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  message: {
    marginTop: spacing.md,
    color: palette.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  tabRail: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  tabButton: {
    minHeight: 38,
    paddingHorizontal: spacing.md,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panel,
    justifyContent: 'center',
  },
  tabButtonActive: {
    borderColor: palette.accent,
    backgroundColor: '#1b2b47',
  },
  tabButtonText: {
    color: palette.textMuted,
    fontSize: 13,
    fontWeight: '600',
  },
  tabButtonTextActive: {
    color: palette.text,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  sectionCopy: {
    color: palette.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  liveActionBlock: {
    marginTop: spacing.lg,
    gap: spacing.sm,
  },
  liveFieldLabel: {
    color: palette.text,
    fontSize: 13,
    fontWeight: '700',
  },
  inlineHint: {
    marginTop: spacing.sm,
    color: palette.textMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  sessionChipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  sessionChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelElevated,
    paddingHorizontal: spacing.sm,
    paddingVertical: 7,
  },
  sessionChipActive: {
    borderColor: palette.accent,
    backgroundColor: '#1b2b47',
  },
  sessionChipText: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  sessionChipTextActive: {
    color: palette.text,
  },
  actionButton: {
    marginTop: spacing.xs,
    minHeight: 42,
    borderRadius: 10,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  actionButtonText: {
    color: palette.bg,
    fontSize: 13,
    fontWeight: '700',
  },
  quickControlRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  quickControlButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.panelElevated,
    paddingHorizontal: spacing.md,
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickControlButtonText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: '700',
  },
  liveWrap: {
    marginTop: spacing.lg,
    gap: spacing.md,
  },
  liveStatusGrid: {
    gap: spacing.sm,
  },
  liveStatusItem: {
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 12,
    backgroundColor: palette.panelElevated,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: 4,
  },
  liveStatusLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  liveStatusValue: {
    color: palette.text,
    fontSize: 13,
    lineHeight: 18,
  },
  webviewShell: {
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: '#060b14',
    minHeight: 560,
  },
  webview: {
    minHeight: 560,
    backgroundColor: '#060b14',
  },
});
