import type { MobilePageCopy, MobileUiLanguage } from './copy-types';

export const MOBILE_PAGE_COPY: Record<MobileUiLanguage, MobilePageCopy> = {
  en: {
    language: 'en',
    title: 'Calder Mobile Control',
    heroKicker: 'Secure Mobile Bridge',
    heading: 'Calder Mobile Control',
    heroBody: 'Enter the one-time code from desktop to unlock your live terminal stream and controls.',
    otpPlaceholder: '000000',
    verifyConnect: 'Verify & Connect',
    otpMeta: 'Pairing expires automatically and can be used only once.',
    otpHelper: 'Use the 6-digit OTP shown under the desktop QR. Do not enter the manual passphrase here.',
    waitingOtp: 'Waiting for OTP…',
    modePending: 'Mode: pending',
    stateIdle: 'State: idle',
    connectionFlowLabel: 'Connection flow',
    stageVerify: '1 Verify',
    stageStream: '2 Stream',
    stageControl: '3 Control',
    waitingForSessions: 'Waiting for sessions…',
    sessionSelectorLabel: 'Session selector',
    switchButton: 'Switch',
    sessionRoutingUnavailable: 'Session routing is unavailable until secure connection is ready.',
    mobileViewsLabel: 'Mobile views',
    terminalTab: 'Terminal',
    browserTab: 'Browser',
    controlsTab: 'Controls',
    clearButton: 'Clear',
    copyButton: 'Copy',
    followOnButton: 'Follow On',
    followOffButton: 'Follow Off',
    commandDeck: 'Command deck',
    showShortcutsButton: 'Show shortcuts',
    hideShortcutsButton: 'Hide shortcuts',
    shortcutsHiddenUntilNeeded: 'Shortcuts stay hidden until you need them.',
    shortcutsHiddenUntilReady: 'Shortcuts stay hidden until secure connection is ready.',
    readonlyHint: 'Read-only mode is active. You can watch terminal output but cannot send commands.',
    repeatInputHint: 'Tap and hold arrows/backspace for repeat input.',
    commandInputPlaceholder: 'Type a command and press Enter',
    prevButton: 'Prev',
    nextButton: 'Next',
    sendButton: 'Send',
    suggestedCommandsLabel: 'Suggested commands',
    quickControlsLabel: 'Quick controls',
    quickControlsTitle: 'Quick controls',
    browserControlDeckTitle: 'Browser controls',
    browserSessionSelectorLabel: 'Browser session',
    browserNoSessionsAvailable: 'No browser sessions available',
    browserStatusWaiting: 'Waiting for browser session catalog…',
    browserStatusReadonly: 'Browser controls require read-write mode.',
    browserStatusReadyTemplate: 'Active browser: {name}',
    browserBackButton: 'Back',
    browserForwardButton: 'Forward',
    browserReloadButton: 'Reload',
    browserInspectButton: 'Inspect',
    browserResponsiveButton: 'Responsive',
    browserPhoneButton: 'iPhone 14',
    browserInspectSelectionNone: 'No inspect selection yet. Enable inspect and tap an element.',
    browserInspectSelectionTemplate: 'Selected element: {summary}',
    browserInspectInputPlaceholder: 'Explain what to do with the selected element',
    browserInspectSendButton: 'Send Inspect Prompt',
    browserInspectInstructionRequired: 'Write an inspect instruction before sending.',
    browserInspectNeedSelection: 'Select a browser element in inspect mode first.',
    browserInspectSubmitting: 'Sending inspect prompt…',
    browserInspectSucceeded: 'Inspect prompt delivered to active CLI session.',
    browserInspectFailedTemplate: 'Inspect prompt failed: {reason}',
    browserControlApplying: 'Applying browser action…',
    browserControlSucceededTemplate: 'Browser action applied: {action}',
    browserControlFailedTemplate: 'Browser action failed: {reason}',
    modePrefix: 'Mode',
    statePrefix: 'State',
    modeReadonly: 'read-only',
    modeReadwrite: 'read-write',
    mobileTerminalCleared: 'Mobile terminal view cleared.',
    nothingToCopyYet: 'Nothing to copy yet.',
    clipboardApiUnavailable: 'Clipboard API is unavailable on this browser.',
    terminalCopied: 'Terminal output copied to clipboard.',
    terminalCopyFailed: 'Could not copy terminal output.',
    switchingSession: 'Switching active session…',
    noShareableSessions: 'No shareable terminal sessions are currently available.',
    activeSessionTemplate: 'Active session: {name}',
    chooseSessionAndSwitch: 'Choose a session and tap Switch.',
    noSessionsAvailable: 'No sessions available',
    switchedToTemplate: 'Switched to {name}.',
    switchFailedTemplate: 'Could not switch session: {reason}',
    unknownReason: 'Unknown reason.',
    connectedLiveStream: 'Connected. Live stream active.',
    channelOpenWaitingAuth: 'Channel open, waiting for host authentication challenge…',
    connectionClosed: 'Connection closed.',
    authFailedTemplate: 'Authentication failed: {reason}',
    hostEndedSession: 'Host ended the shared session.',
    answerDelivered: 'Answer delivered. Waiting for host confirmation…',
    missingPairingToken: 'Missing pairing token.',
    enterOtpPrompt: 'Enter the 6-digit one-time code from desktop.',
    verifyingOtp: 'Verifying one-time code…',
    connectionFailed: 'Connection failed.',
    couldNotDecodeConnectionCode: 'Could not decode connection code.',
    connectionCodeTooShort: 'Connection code is too short.',
    wrongPassphraseOrInvalidCode: 'Secure handshake could not be verified. QR pairing may be stale or expired. Generate a new QR on desktop and try again.',
    malformedConnectionPayload: 'Connection code payload is malformed.',
    missingConnectionFields: 'Connection code is missing fields.',
    connectionTypeMismatch: 'Connection code type mismatch.',
    serverMessage: {
      pairingExpired: 'Pairing expired.',
      tooManyPairingAttempts: 'Too many pairing attempts. Please wait and try again.',
      requestBodyTooLarge: 'Request body too large.',
      invalidJsonPayload: 'Invalid JSON payload.',
      pairingTokenInvalid: 'Pairing token is invalid.',
      tooManyOtpAttempts: 'Too many OTP attempts.',
      otpMismatch: 'One-time code mismatch.',
      tooManyAnswerSubmissions: 'Too many answer submissions. Please wait and retry.',
      tooManyChallengeRequests: 'Too many auth requests. Please wait and retry.',
      otpRequiredFirst: 'OTP verification is required first.',
      answerAlreadySubmitted: 'Answer has already been submitted for this pairing.',
      submitTokenInvalid: 'Submit token is invalid.',
      missingAnswerPayload: 'Missing answer payload.',
      invalidAnswerPayload: 'Answer payload is invalid.',
      missingChallengePayload: 'Missing auth challenge payload.',
      invalidChallengePayload: 'Auth challenge payload is invalid.',
      pairingNotFound: 'Pairing not found.',
      invalidPairingTokenPage: 'Invalid pairing token.',
      routeNotFound: 'Route not found.',
    },
  },
  tr: {
    language: 'tr',
    title: 'Calder Mobil Kontrol',
    heroKicker: 'Güvenli Mobil Köprü',
    heading: 'Calder Mobil Kontrol',
    heroBody: 'Canlı terminal akışını ve kontrolleri açmak için masaüstündeki tek kullanımlık kodu girin.',
    otpPlaceholder: '000000',
    verifyConnect: 'Doğrula ve Bağlan',
    otpMeta: 'Eşleştirme otomatik olarak sona erer ve yalnızca bir kez kullanılabilir.',
    otpHelper: 'Masaüstünde QR altında görünen 6 haneli OTP\'yi girin. Buraya manuel parola girmeyin.',
    waitingOtp: 'OTP bekleniyor…',
    modePending: 'Mod: bekleniyor',
    stateIdle: 'Durum: boşta',
    connectionFlowLabel: 'Bağlantı akışı',
    stageVerify: '1 Doğrula',
    stageStream: '2 Akış',
    stageControl: '3 Kontrol',
    waitingForSessions: 'Oturumlar bekleniyor…',
    sessionSelectorLabel: 'Oturum seçici',
    switchButton: 'Geç',
    sessionRoutingUnavailable: 'Güvenli bağlantı hazır olana kadar oturum yönlendirme kullanılamaz.',
    mobileViewsLabel: 'Mobil görünümler',
    terminalTab: 'Terminal',
    browserTab: 'Tarayıcı',
    controlsTab: 'Kontroller',
    clearButton: 'Temizle',
    copyButton: 'Kopyala',
    followOnButton: 'Takip Açık',
    followOffButton: 'Takip Kapalı',
    commandDeck: 'Komut paneli',
    showShortcutsButton: 'Kısayolları göster',
    hideShortcutsButton: 'Kısayolları gizle',
    shortcutsHiddenUntilNeeded: 'İhtiyacınız olana kadar kısayollar gizli kalır.',
    shortcutsHiddenUntilReady: 'Güvenli bağlantı hazır olana kadar kısayollar gizli kalır.',
    readonlyHint: 'Salt okunur mod etkin. Terminal çıktısını izleyebilirsiniz ancak komut gönderemezsiniz.',
    repeatInputHint: 'Tekrarlı giriş için ok/backspace tuşlarına basılı tutun.',
    commandInputPlaceholder: 'Komut yazın ve Enter\'a basın',
    prevButton: 'Önceki',
    nextButton: 'Sonraki',
    sendButton: 'Gönder',
    suggestedCommandsLabel: 'Önerilen komutlar',
    quickControlsLabel: 'Hızlı kontroller',
    quickControlsTitle: 'Hızlı kontroller',
    browserControlDeckTitle: 'Tarayıcı kontrolleri',
    browserSessionSelectorLabel: 'Tarayıcı oturumu',
    browserNoSessionsAvailable: 'Tarayıcı oturumu yok',
    browserStatusWaiting: 'Tarayıcı oturum kataloğu bekleniyor…',
    browserStatusReadonly: 'Tarayıcı kontrolleri için okuma-yazma modu gerekir.',
    browserStatusReadyTemplate: 'Aktif tarayıcı: {name}',
    browserBackButton: 'Geri',
    browserForwardButton: 'İleri',
    browserReloadButton: 'Yenile',
    browserInspectButton: 'Inspect',
    browserResponsiveButton: 'Responsive',
    browserPhoneButton: 'iPhone 14',
    browserInspectSelectionNone: 'Henüz inspect seçimi yok. Inspect modunu açıp bir elemana dokunun.',
    browserInspectSelectionTemplate: 'Seçili element: {summary}',
    browserInspectInputPlaceholder: 'Seçili element ile ne yapılacağını yazın',
    browserInspectSendButton: 'Inspect Prompt Gönder',
    browserInspectInstructionRequired: 'Göndermeden önce bir inspect talimatı yazın.',
    browserInspectNeedSelection: 'Önce inspect modunda bir tarayıcı elementi seçin.',
    browserInspectSubmitting: 'Inspect prompt gönderiliyor…',
    browserInspectSucceeded: 'Inspect prompt aktif CLI oturumuna iletildi.',
    browserInspectFailedTemplate: 'Inspect prompt başarısız: {reason}',
    browserControlApplying: 'Tarayıcı aksiyonu uygulanıyor…',
    browserControlSucceededTemplate: 'Tarayıcı aksiyonu uygulandı: {action}',
    browserControlFailedTemplate: 'Tarayıcı aksiyonu başarısız: {reason}',
    modePrefix: 'Mod',
    statePrefix: 'Durum',
    modeReadonly: 'salt okunur',
    modeReadwrite: 'okuma-yazma',
    mobileTerminalCleared: 'Mobil terminal görünümü temizlendi.',
    nothingToCopyYet: 'Henüz kopyalanacak içerik yok.',
    clipboardApiUnavailable: 'Bu tarayıcıda panoya kopyalama API\'si kullanılamıyor.',
    terminalCopied: 'Terminal çıktısı panoya kopyalandı.',
    terminalCopyFailed: 'Terminal çıktısı kopyalanamadı.',
    switchingSession: 'Aktif oturuma geçiliyor…',
    noShareableSessions: 'Şu anda paylaşılabilir terminal oturumu yok.',
    activeSessionTemplate: 'Aktif oturum: {name}',
    chooseSessionAndSwitch: 'Bir oturum seçin ve Geç\'e dokunun.',
    noSessionsAvailable: 'Oturum yok',
    switchedToTemplate: '{name} oturumuna geçildi.',
    switchFailedTemplate: 'Oturum değiştirilemedi: {reason}',
    unknownReason: 'Bilinmeyen neden.',
    connectedLiveStream: 'Bağlandı. Canlı akış aktif.',
    channelOpenWaitingAuth: 'Kanal açıldı, ana makine kimlik doğrulama isteği bekleniyor…',
    connectionClosed: 'Bağlantı kapandı.',
    authFailedTemplate: 'Kimlik doğrulama başarısız: {reason}',
    hostEndedSession: 'Ana makine paylaşılan oturumu sonlandırdı.',
    answerDelivered: 'Yanıt gönderildi. Ana makine onayı bekleniyor…',
    missingPairingToken: 'Eşleştirme belirteci eksik.',
    enterOtpPrompt: 'Masaüstündeki 6 haneli tek kullanımlık kodu girin.',
    verifyingOtp: 'Tek kullanımlık kod doğrulanıyor…',
    connectionFailed: 'Bağlantı başarısız.',
    couldNotDecodeConnectionCode: 'Bağlantı kodu çözümlenemedi.',
    connectionCodeTooShort: 'Bağlantı kodu çok kısa.',
    wrongPassphraseOrInvalidCode: 'Güvenli el sıkışma doğrulanamadı. QR eşleştirmesi eski veya süresi dolmuş olabilir. Masaüstünde yeni QR üretip tekrar deneyin.',
    malformedConnectionPayload: 'Bağlantı kodu verisi bozuk.',
    missingConnectionFields: 'Bağlantı kodunda gerekli alanlar eksik.',
    connectionTypeMismatch: 'Bağlantı kodu türü eşleşmiyor.',
    serverMessage: {
      pairingExpired: 'Eşleştirme süresi doldu.',
      tooManyPairingAttempts: 'Çok fazla eşleştirme denemesi yapıldı. Lütfen bekleyip tekrar deneyin.',
      requestBodyTooLarge: 'İstek gövdesi çok büyük.',
      invalidJsonPayload: 'Geçersiz JSON verisi.',
      pairingTokenInvalid: 'Eşleştirme belirteci geçersiz.',
      tooManyOtpAttempts: 'Çok fazla OTP denemesi yapıldı.',
      otpMismatch: 'Tek kullanımlık kod eşleşmedi.',
      tooManyAnswerSubmissions: 'Çok fazla yanıt gönderimi yapıldı. Lütfen bekleyip tekrar deneyin.',
      tooManyChallengeRequests: 'Çok fazla kimlik doğrulama isteği yapıldı. Lütfen bekleyip tekrar deneyin.',
      otpRequiredFirst: 'Önce OTP doğrulaması gerekli.',
      answerAlreadySubmitted: 'Bu eşleştirme için yanıt zaten gönderildi.',
      submitTokenInvalid: 'Gönderim belirteci geçersiz.',
      missingAnswerPayload: 'Yanıt verisi eksik.',
      invalidAnswerPayload: 'Yanıt verisi geçersiz.',
      missingChallengePayload: 'Kimlik doğrulama isteği verisi eksik.',
      invalidChallengePayload: 'Kimlik doğrulama isteği verisi geçersiz.',
      pairingNotFound: 'Eşleştirme bulunamadı.',
      invalidPairingTokenPage: 'Geçersiz eşleştirme belirteci.',
      routeNotFound: 'Rota bulunamadı.',
    },
  },
};
