import { MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_FINALIZE } from './page-script-runtime-bootstrap-finalize';
import { MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS } from './page-script-runtime-bootstrap-listeners';
import { MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_PREFLIGHT } from './page-script-runtime-bootstrap-preflight';

export const MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP = `${MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_PREFLIGHT}${MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS}${MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_FINALIZE}`;
