import { MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS_CONNECT } from './page-script-runtime-bootstrap-listeners-connect';
import { MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS_CONTROLS } from './page-script-runtime-bootstrap-listeners-controls';
import { MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS_SURFACE } from './page-script-runtime-bootstrap-listeners-surface';
import { MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS_TERMINAL } from './page-script-runtime-bootstrap-listeners-terminal';

export const MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS = `${MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS_CONNECT}${MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS_TERMINAL}${MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS_CONTROLS}${MOBILE_PAGE_SCRIPT_RUNTIME_BOOTSTRAP_LISTENERS_SURFACE}`;
